heatstroke/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('sensor/', include('sensor.urls')),
    path("", views.index, name="index"),
    path("information", views.information, name="information"),
    path("login/", views.user_login, name="login"),
    path('logout/', views.user_logout, name='logout'),
    path("register/", views.register, name="register"),
    path("member_dashboard/", views.member_dashboard, name="member_dashboard"),
    path("", include("level.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

level/urls.py
from django.urls import path
from .views import create_group, group_admin_dashboard, view_group, add_member, update_profile, user_profile # นำเข้า View ที่เราจะใช้

urlpatterns = [
    path("create-group/", create_group, name="create_group"),  # URL สำหรับสร้าง Group
    path("group-admin-dashboard/", group_admin_dashboard, name="group_admin_dashboard"),
    path("group/<int:group_id>/", view_group, name="view_group"),
    path("group/<int:group_id>/add-member/", add_member, name="add_member"),
    path('profile/<int:user_id>/', user_profile, name='user_profile'),
    path('profile/<int:user_id>/update/', update_profile, name='update_profile'),
]

sensor/urls.py
from django.urls import path
from .views import receive_sensor_data, display_data

app_name = "sensor"  # ใช้ namespace

urlpatterns = [
    path("receive/", receive_sensor_data, name="receive_sensor_data"),  # รับข้อมูลจากเซ็นเซอร์
    path("display_data/", display_data, name="display_data"),  # แสดงข้อมูลเซ็นเซอร์
]

templates/add_member.html
{% extends "base.html" %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block title %} {{ group.name }} {% endblock %}

{% block content %}
    <!-- ✅ ฟอร์ม Add Member -->
   <div class="group-details">
    <h1>Add Member</h1>
    <div>
    <form method="post" action="{% url 'add_member' group.id %}">
        {% csrf_token %}
        <label for="user_id"> User ID:</label>
        <input type="number" id="user_id" name="user_id" required>
        <br>
        <button type="submit" class="btn-submit">Add Member</button>
    </form>

    {% if messages %}
        {% for message in messages %}
            <p class="message">{{ message }}</p>
        {% endfor %}
    {% endif %}
    </div>
    <br>
    <a href="{% url 'view_group' group.id %}" class="btn-back-home">Back</a>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Hide side {% endblock %}</title>
    {% block style %}{% endblock %}
</head>
<body class="{% block body_class %}{% endblock %}">
    <header>
        {% block header  %}
        <h1><a href="{% url 'index' %}" class="green-link">Heatstroke Risk Estimation</a></h1>
        <!-- ปุ่ม toggle อยู่ใน header -->
        <label for="sidebar-toggle" class="sidebar-toggle">☰</label>
        {% endblock  %}
    </header>
    <input type="checkbox" id="sidebar-toggle" class="sidebar-checkbox">
    <div class="sidebar" id="sidebar">
        {% block sidebar  %}
        <ur>
            <li><a href="{% url 'index' %}">HOME</a></li>
            <li><a href="{% url 'information' %}">INFORMATION</a></li>
            <li>ABOUT</li>
            <li><a href="{% url 'logout' %}">LOGOUT</a></li>
        </ur>
        {% endblock  %}
    </div>
    <div class="content" id="content">
            {% block content %} {% endblock %}
    </div>
    <div class="content2" id="content2">
            {% block content2 %} {% endblock %}
    </div>
</body>
</html>

templates/create_group.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block title %} Greate Group {% endblock %}

{% block content %}
    <div class="form-container">
        <h2>Create a New Group</h2>

        {% if messages %}
            {% for message in messages %}
                <p class="message">{{ message }}</p>
            {% endfor %}
        {% endif %}

        <form method="post">
            {% csrf_token %}
            
            <label for="group_name">Group Name:</label>
            <input type="text" id="group_name" name="group_name" required>

            <label for="description">Description:</label>
            <textarea id="description" name="description"></textarea>

            <button type="submit" class="btn-submit">Create Group</button>
        </form>
        <br>
        <a href="{% url 'group_admin_dashboard' %}" class="btn-back-home">Back</a>
    </div>
{% endblock %}

templates/group_admin_dashboard.html
{% extends "base.html" %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block title %} HOME {% endblock %}
{% block content%}
    <h1>Hi {{ request.user.username }}!</h1>
    <h2>These are your Group!</h2>
    <br>
    <a href="{% url 'create_group' %}" class="btn-join-group">Create Group</a>
    <br>
    <ul class="group-list">
        {% for group in user_groups %}
            <li class="group-item">
                <strong>{{ group.name }}</strong> - Created on: {{ group.created_at|date:"d M Y" }}
                <a href="{% url 'view_group' group.id %}"class="btn-join-group">View Group</a>
            </li>
        {% empty %}
            <p>You are not an admin of any group.</p>
        {% endfor %}
    </ul>
{% endblock  %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block title %} HOME {% endblock %}
{% block content%}
    <h1>Hi {{ request.user.username }}!</h1>
    <h2>These are your information!</h2>
    <url>
        <li>Heart Rate :</li>
        <li>Core Temperature :</li>
        <li>Ambient Temperature :</li>
        <li>Humidity :</li>
        <li>Galvanic Skin Response :</li>
    </url>
    <br>
    <a href="{% url 'sensor:display_data' %}" class="btn-sensor-data">📊 View Sensor Data</a>
{% endblock  %}

templates/information.html
{% extends "base.html" %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block title %} INFORMATION {% endblock %}
{%block content%}
    <h1>โรคลมร้อน คืออะไร?</h1>
    <p>โรคลมร้อน หรือ Heatstroke มักพบในช่วงหน้าร้อน โดยเกิดจากสภาพอากาศที่ร้อนจัด 
    ทำให้อุณหภูมิในร่างกายสูงขึ้นอย่างรวดเร็ว จนไม่สามารถระบายความร้อนออกได้ทันที
    โดยโรคนี้เมื่อเกิดอาการควรได้รับการรักษาทันทีเนื่องจากมีโอกาสเสียชีวิตสูงมาก</p>
{%endblock%}
{% block content2%}
    <h1>อาการของโรคลมร้อน</h1>
    <ul>
        <li>มีไข้สูงเกิน 40.5 องศาเซลเซียส</li>
        <li>ปวดหัวศีรษะ หน้ามืด เมื่อยหล้า อ่อนเพลีย และอาจหมดสติได้ </li>
        <li>มีความผิดปกติทางระบบประสาท เช่น ชัก เพ้อ เดินโซเซ ตอบสนองช้า พูดจาสับสน</li>
        <li>ไม่มีเหงื่อออก จากผลของต่อมเหงื่อทำงานผิดปกติทำให้ผิวหนังเปลี่ยนเป็นสีแดงากขึ้น</li>
        <li>อาจพบปัสสาวะสีเข้มผิดปกติจากภาวะกล้ามเนื้อลายสลาย และอาจเกิดภาวะไตวายตามมาได้</li>
    </ul>
    <br>
    <h1>การปฐมพยาบาลเบื้องต้น</h1>
    <ul>
        <li>การทำให้อุณหภูมิร่างกายลดลงให้เร็วที่สุดก่อนนำส่งโรงพยาบาล</li>
        <li>ย้ายผู้ป่วยมาในที่ร่ม และจัดท่าให้อยู่ในท่าหงาย</li>
        <li>ใช้ผ้าชุบน้ำเย็นหรือน้ำแข็งประคบตามร่างกาย โดยเฉพาะบริเวณหลังคอ รักแร้ และนำพัดลมเป่าระบายความร้อน</li>
        <li>หากผู้ป่วยรู้สึกตัวให้ดื่มน้ำเกลือให้มากที่สุด เพื่อทดแทนภาวะการขาดน้ำ</li>
        <li>นำผู้ป่วยส่งโรงพยาบาลให้เร็วที่สุด</li>
    </ul>
    
{% endblock  %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LOGIN</title>
    {% load static %}
    {% block style %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}
</head>
<body class="login">
    <div class="login-right">
        <div class="login-form-container">
        <h1>LOGIN</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Login</button>
        </form>
        <p>Don't have an account? <a href="{% url 'register' %}">REGISTER NOW!</a></p>
    </div>
</div>
</body>
</html>

templates/receive.html
{% extends "base.html" %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block title %} HOME {% endblock %}
{% block content%}
    <h1>Received Sensor Data</h1>
    <p>Temperature: {{ temperature }}°C</p>
    <p>Humidity: {{ humidity }}%</p>
    <p>Body Temperature: {{ body_temp }}°C</p>
    <p>Heart Rate: {{ heart_rate }}BPM</p>
    <p>Skin resistance: {{ skin_resistance }}</p>
    <p>Risk: {{ risk }}</p>
    <br>
    <a href="{% url 'sensor:display_data' %}" class="btn-join-group">View Sensor Data</a>
    <a href="{% url 'user_profile' user_id=request.user.id %}" class="btn-join-group">Your Profile</a>
    <a href="{% url 'sensor:receive_sensor_data' %}" class="btn-join-group">Fill Sensor Data</a>
    
{% endblock  %}

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>REGISTER</title>
    {% load static %}
    {% block style %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}
</head>
<body class="login">
    <div class="login-right">
        <div class="login-form-container">
            <h1>REGISTER</h1>
            <form method="post">
                {% csrf_token %}
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required><br>
            
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" required><br>
            
                <label for="password1">Password:</label>
                <input type="password" id="password1" name="password1" required><br>
            
                <label for="password2">Confirm Password:</label>
                <input type="password" id="password2" name="password2" required><br>

                <select name="role">
                    <option value="member">สมาชิกกลุ่ม</option>
                    <option value="group_admin">ผู้ดูแลกลุ่ม</option>
                </select>
                <br>
                <button type="submit" >Register</button>
            </form>
        
            <p>Already have an account? <a href="{% url 'login' %}">Login here</a></p>
                <!-- แสดงข้อความแจ้งเตือน -->
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        </div>
    </div>
</body>
</html>

templates/sensor_data_form.html
{% extends "base.html" %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block title %} Enter Sensor Data {% endblock %}

{% block content %}
    <h1>Enter Sensor Data</h1>
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}  <!-- ฟอร์มจะถูกแสดงในรูปแบบพารากราฟ -->
        <button type="submit">Submit</button>
    </form>

{% endblock %}

templates/update_profile.html
{% extends "base.html" %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block title %} Update Profile {% endblock %}

{% block content %}
  <h2>Update Your Profile</h2>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Changes</button>
  </form>
  <a href="{% url 'user_profile' user_id=request.user.id %}" class="btn-join-group">Back</a>
{% endblock %}

templates/user_profile.html
{% extends "base.html" %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block title %} Profile {% endblock %}

{% block content %}
  <h2>User Profile</h2>
  
  <div>
    <p><strong>First Name:</strong> {{ user.first_name }}</p>
    <p><strong>Last Name:</strong> {{ user.last_name }}</p>
    <p><strong>Username:</strong> {{ user.username }}</p>
    <p><strong>Email:</strong> {{ user.email }}</p>
    <p><strong>Role:</strong> {{ user.role }}</p>
    <p><strong>Age:</strong> {{ user.age }}</p>
    <p><strong>Height:</strong> {{ user.height }} cm</p>
    <p><strong>Weight:</strong> {{ user.weight }} kg</p>
    <a href="{% url 'update_profile' user_id=request.user.id %}" class="btn-join-group">Edit Profile</a>
  </div>
  <br>
  <a href="{% url 'index' %}" class="btn-back-home">Back</a>


{% endblock %}

templates/view_group.html
{% extends "base.html" %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block title %} {{ group.name }} {% endblock %}

{% block content %}
        <!-- ✅ ส่วนรายละเอียดกลุ่ม (ซ้าย) -->
        <div class="group-details">
            <h1>{{ group.name }}</h1>
            <p><strong>Description:</strong> {{ group.description }}</p>
            <p><strong>Created by:</strong> {{ group.created_by.username }}</p>
            <p><strong>Created on:</strong> {{ group.created_at|date:"d M Y" }}</p>
            <br>
            <a href="{% url 'group_admin_dashboard' %}" class="btn-back-home">Back</a>
            <a href="{% url 'add_member' group.id %}" class="btn-join-group">Add Member</a>
        </div>
{% endblock %}
{% block content2 %}
    <div class="member-container">
        <h2>Members</h2>
        <ul class="member-list">
            {% for member in members %}
                <div>
                <a href="{% url 'user_profile' member.id %}">View Profile</a>
                <li>{{ member.username }} (ID: {{ member.id }})</li>
                </div>
            {% empty %}
                <p>No members in this group yet.</p>
            {% endfor %}
        </ul>
    </div>
{% endblock %}